### ISSUE TITLE
build page of our world nomads website

### ISSUE THREAD

**Issue by sasha-astiadi** [ourworld-tsc/www_ournomads#1]
- [x] copy images and texts from ai file
- [x] create your own branch development_name
- [x] build homepage
- [x] build location page
- [x] build co-owns page
- [x] hand in to ops to be build the website, ask kristof which domain he prefer / to buy

**Comment by sasha-astiadi** [comment]
first preview https://nomads.ourworld.tf/

**Comment by sasha-astiadi** [comment]
all pages built on https://nomads.ourworld.tf/

**Comment by remrekoc** [comment]
all pages are not complete yet @sasha-astiadi. I'm still gathering content for the co-own page.
